Repository theforeman/foreman_chef, pull requests merged in 2019-09, with the labels that each got.

#92 Fixes #27626 - Fix icon path for facts
  app/models/foreman_chef/fact_name.rb
Labels: Needs testing

#90 Fix config report origin icon
  app/helpers/foreman_chef/chef_reports_helper.rb
Labels: Needs testing, Not yet reviewed

#91 Refs #26393 - import boot time fact
  app/models/foreman_chef/fact_parser.rb
Labels: Ready to merge

#93 Fixes #27820 - setting initialization init
  app/models/setting/foreman_chef.rb
Labels: Needs testing
